apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: /
spec:
  ingressClassName: azure-application-gateway # might raise a bug. retry.
  rules:
  - http:
      paths:
      - pathType: Exact
        path: /allocation
        backend:
          service:
            name: allocation-be-svc
            port:
              number: 80
      - pathType: Exact
        path: /timetable
        backend:
          service:
            name: timetable-fe-svc
            port:
              number: 80
      - pathType: Exact
        path: /security
        backend:
          service:
            name: timetable-be-svc
            port:
              number: 80
      - pathType: Exact
        path: /optimization
        backend:
          service:
            name: optimization-svc
            port:
              number: 80
      - pathType: Exact
        path: /celery
        backend:
          service:
            name: celery-svc
            port:
              number: 80
      - pathType: Exact
        path: /rabbitmq
        backend:
          service:
            name: rabbitmq-svc
            port:
              number: 80
      - pathType: Exact
        path: /
        backend:
          service:
            name: allocation-fe-svc
            port:
              number: 80