apiVersion: v1
kind: Service
metadata:
  name: allocation-be-svc
  labels:
    app: allocation-be
spec:
  type: ClusterIP
  ports:
  -  port: 80
  selector:
    app: allocation-be
---
apiVersion: v1
kind: Service
metadata:
  name: allocation-fe-svc
  labels:
    app: allocation-fe
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: allocation-fe
