name: Destroy AKS cluster
on: 
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      pull-requests: write
      
jobs:
  clean:
    defaults:
      run:
        working-directory: ./overlays/aks_cluster
    name: Destroy stage AKS
    runs-on: ubuntu-latest
    environment:
      name: stage
    env:
      ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
      ARM_USE_AZUREAD: true 
      
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.5.0

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
        -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
        -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}"
      
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -var "parent_resource_group_name=${{secrets.AZURE_RESOURCE_GROUP_NAME}}"